#!/usr/bin/env python
# polxml.py - add Drude oscillators to OpenMM xml force field file.
# Agilio Padua <agilio.padua@ens-lyon.fr>
# version 2024/01/19

import argparse
import random
import xml.etree.ElementTree as ET
import numpy as np


usage = """
==============================================================================
Add Drude oscillators to OpenMM xml force field file and pdb.
------------------------------------------------------------------------------
Format of file containing specification of Drude oscillators (alpha.ff):
  # type  dm/u  dq/e  k/(kJ/molA2)  alpha/A3  thole
  C3H     1.0   0.0   4184.0        1.016     2.6
  ...
* dm is the mass to place on the Drude particle (subtracted from its core),
* dq is the charge to place on the Drude particle (subtracted from its core),
* k is the harmonic force constant of the bond between core and Drude,
* alpha is the polarizability, hyrdogen aroms are not merged,
* thole is a parameter of the Thole damping function.
------------------------------------------------------------------------------
A Drude particle is created for each atom in the xml file
that corresponds to an atom type given in the Drude file.
This script will add new atom types, new bond types, new atoms and
new bonds to the xml file and new particles to the pdb file.
==============================================================================
"""

# --------------------------------------

def hexiflarge(i, ndig):
    """
    Convert number to hex starting with A if more than n digits.
    VMD, OpenMM convention in PDB files with natom > 99999, nmol > 9999
    """

    declim = 10**ndig
    hexlim = int('A' + (ndig-1)*'0', 16)

    if i < declim:
        return f'{i}'
    else:
        i = i - declim + hexlim
        return f'{i:X}'

def intfromhexiflarge(a):
    """
    Convert string containing hex number (large systems) to int.
    VMD, OpenMM convention in PDB files with natom > 99999, nmol > 9999
    """

    if a.strip().isdigit():
        return int(a)
    
    ndig = len(a)
    declim = 10**ndig
    hexlim = int('A' + (ndig-1)*'0', 16)

    i = int(a, 16)
    return i - hexlim + declim

# --------------------------------------

class Topology(object):
    '''topology and coordinates from pdb file'''

    def __init__(self, pdbfile):
        '''read from pdb file'''

        self.box = ''
        self.atoms = []
        self.bonds = []
        self.natom = 0
        self.ndrude = 0

        with open(pdbfile, 'r') as f:
            line = f.readline()
            while 'CRYST1' not in line:
                line = f.readline()
            self.box = line.strip()
            line = f.readline()
            while not (line.startswith('ATOM') or line.startswith('HETATM')):
                line = f.readline()
            while 'ATOM' in line or 'HETATM' in line:
                atom = {}
                atom['n'] = intfromhexiflarge(line[6:11])
                atom['name'] = line[12:16].strip()
                atom['mol'] = line[17:20].strip()
                atom['seq'] = intfromhexiflarge(line[22:26])
                atom['x'] = float(line[30:38])
                atom['y'] = float(line[38:46])
                atom['z'] = float(line[46:54])
                atom['ele'] = line[76:78].strip()
                atom['nH'] = 0         # number of bonded H
                atom['type'] = ''      # non-bonded type
                atom['class'] = ''     # bonded type
                self.atoms.append(atom)
                line = f.readline()
            while 'CONECT' in line:
                i = intfromhexiflarge(line[6:11]) - 1
                j = intfromhexiflarge(line[11:16]) - 1
                if self.atoms[i]['seq'] != self.atoms[j]['seq']:
                    print(f'bond between atoms {i:d} and {j:d} of different molecules')
                    exit(1)
                self.bonds.append({'i': i, 'j': j})
                line = f.readline()
        self.natom = len(self.atoms)

    def write(self, pdbfile):
        '''write topology to PDB file'''

        with open(pdbfile, 'w') as f:
            f.write('TITLE     created by polxml\n')
            f.write('REMARK    includes Drude particles\n')
            f.write(self.box + '\n')
            n = 0
            for at in self.atoms:
                n += 1
                atidx = hexiflarge(n, 5)
                molidx = hexiflarge(at['seq'], 4)
                f.write('HETATM{0:>5s} {1:4s} {2:3s}  {3:>4s}    '\
                        '{4:8.3f}{5:8.3f}{6:8.3f}  1.00  0.00          '\
                        '{7:>2s}\n'.format(atidx, at['name'][:4], at['mol'], molidx,
                        at['x'], at['y'], at['z'], at['ele']))
                if len(at['name']) > 4:
                    print('warning: atom name {} too long in pdb'.format(at['name']))
            for bd in self.bonds:
                atidx_i = hexiflarge(bd.i + 1, 5)
                atidx_j = hexiflarge(bd.j + 1, 5)
                f.write('CONECT{0:>5s}{1:>5s}\n'.format(atidx_i, atidx_j))
            f.write('END\n')

    def settypes(self, ff):
        '''assign types from ff to atoms in topology'''

        for at in self.atoms:
            for res in ff.root.iter('Residue'):
                resname = res.get('name').replace('-', '').replace('+', '')[:3]
                if at['mol'] == resname:
                    for ffatom in res.iter('Atom'):
                        if at['name'] == ffatom.get('name'):
                            at['type'] = ffatom.get('type').split('-')[1]
                            for attype in ff.root.iter('Type'):
                                if at['type'] == attype.get('name').split('-')[1]:
                                    at['class'] = attype.get('class')
                                    break
                            break
                    break

    def countbondedH(self):
        '''count H bonded to each atom (to merge polarizabilities)'''

        for bd in self.bonds:
            i = bd['i']
            j = bd['j']
            if self.atoms[i]['name'][0] in 'Hh':
                self.atoms[j]['nH'] += 1
            elif self.atoms[j]['name'][0] in 'Hh':
                self.atoms[i]['nH'] += 1

    def checknH(self):
        '''check if each non-bonded type has same number of bonded H'''

        attype = [at['type'] for at in self.atoms]
        atnh = [at['nH'] for at in self.atoms]
        types = list(set(attype))
        nh = [-1] * len(types)
        for at, n in zip(attype, atnh):
            i = types.index(at)
            if nh[i] == -1:
                nh[i] = n
            elif nh[i] != n:
                print(f'atom type {at} with different numbers of bonded H')
                exit(1)

    def polarize(self, ff, eps=0.02):
        '''add Drude particles and bonds to topology'''

        dplist = []
        for res in ff.root.iter('Residue'):
            resname = res.get('name').replace('-', '').replace('+', '')[:3]
            for ffatom in res.iter('Atom'):
                if 'core' in ffatom.attrib:
                    dp = {'name': ffatom.get('name'),
                          'core': ffatom.get('core'),
                          'mol': resname}
                    dplist.append(dp)

        # add DP after each core
        natoms = len(self.atoms)
        random.seed(1234)
        i = 0
        self.ndrude = 0
        while i < natoms:
            atom = self.atoms[i]
            for dp in dplist:
                if atom['mol'] == dp['mol'] and atom['name'] == dp['core']:
                    ndp = {}
                    ndp['name'] = dp['name']
                    ndp['mol'] = atom['mol']
                    ndp['seq'] = atom['seq']
                    ndp['x'] = atom['x'] + eps * (2*random.random() - 1.0)
                    ndp['y'] = atom['y'] + eps * (2*random.random() - 1.0)
                    ndp['z'] = atom['z'] + eps * (2*random.random() - 1.0)
                    ndp['ele'] = 'EP'
                    i += 1
                    self.atoms.insert(i, ndp)
                    self.ndrude += 1
                    natoms += 1
                    # increment indices in bonds
                    for bond in self.bonds:
                        if bond['i'] >= i:
                            bond['i'] += 1
                        if bond['j'] >= i:
                            bond['j'] += 1
                    # no need to add DC-CP bonds
                    #self.bonds.append({'i': i - 1, 'j': i})
                    break
            i += 1

# --------------------------------------

fpe0 =  0.0007197587     # (4 Pi eps0) in e^2/(kJ/mol A)

class Drude(object):
    """specification of drude oscillator types"""

    def __init__(self, drudefile, config, ff):
        self.types = []
        self.alpha_H = 0.323           # PCCP 20(2018)10992

        with open(drudefile, "r") as f:

            # search for polarizability of H
            for line in f:
                line = line.strip()
                if line.startswith('#') or len(line) == 0:
                    continue
                if line.startswith('H'):
                    tok = line.split()
                    self.alpha_H = float(tok[4])
                    break
            f.seek(0)

            config.countbondedH()
            config.settypes(ff)
            config.checknH()

            for line in f:
                line = line.strip()
                if line.startswith('#') or len(line) == 0:
                    continue
                tok = line.split()

                if tok[0].startswith('H'):
                    if float(tok[4]) != self.alpha_H:
                        print('warning: different polarizabilities for H')
                    continue

                drude = {}
                drude['type'] = tok[0]
                drude['dm'] = float(tok[1])
                # dq = float(tok[2])
                drude['k'] = float(tok[3])
                alpha = float(tok[4])
                drude['thole'] = float(tok[5])

                for att in config.atoms:
                    if drude['type'] == att['type']:
                        alpha += att['nH'] * self.alpha_H
                        break
                drude['alpha'] = alpha

                dq = (fpe0 * drude['k'] * alpha)**0.5
                drude['dq'] = -abs(dq)

                self.types.append(drude)


# --------------------------------------


class Forcefield(object):
    '''force field from OpenMM xml file'''

    def __init__(self, infile):
        '''element tree from xml file'''

        self.ftree = ET.parse(infile)
        self.root = self.ftree.getroot()

        atomtypes = self.root.find('AtomTypes')
        for atom in atomtypes:
            atname = atom.get('name')
            tok = atname.split('-')
            if len(tok) < 3:
                print('error: input xml file does not have unique atom names; use fftool with --types')
                exit(1)

    def write(self, outfile):
        '''write force field to xml file'''

        for res in self.root.iter('Residue'):
            for atom in res.iter('Atom'):
                if 'core' in atom.attrib:
                    atom.attrib.pop('core')

        ET.indent(self.root, space=' ')
        self.ftree.write(outfile)

    def polarize(self, drude):
        '''add Drude dipoles to force field'''
        
        atomtypes = self.root.find('AtomTypes')
        for atom in atomtypes:
            atname = atom.get('name')
            tok = atname.split('-')
            # avoid recursion if mol name same as atom type (ex Cl)
            if atname[0] == 'D' and len(tok) > 3:
                continue
            ffname = tok[1]
            for dt in drude.types:
                if ffname == dt['type']:
                    # add DP to AtomTypes
                    dp = ET.SubElement(atomtypes, 'Type')
                    dp.set('name', 'D-' + atname)
                    dp.set('class', 'DRUD')
                    dp.set('mass', '0.0')
                    # no need to set DP, DC masses: done by OpenMM
                    # dp.set('mass', str(dt['dm']))
                    # subtract Drude mass from DC
                    # dcm = float(atom.attrib['mass'])
                    # dcm -= dt['dm']
                    # atom.set('mass', f'{dcm:.4f}')
                    break

        # check length of atom names (to decide on DP numbering)
        longname = False
        for residue in self.root.iter('Residue'):
            for atom in residue.iter('Atom'):
                if len(atom.get('name')) > 3:
                    longname = True

        for residue in self.root.iter('Residue'):
            i = 0
            cnt = 0     # counter of DP
            for atom in residue.iter('Atom'):
                i += 1
                atname = atom.get('name')
                attype = atom.get('type')
                tok = attype.split('-')
                # avoid recursion if mol name same as atom type (ex Cl)
                if attype[0] == 'D' and len(tok) > 3:
                    continue
                fftype = tok[1]
                for dt in drude.types:
                    if fftype == dt['type']:
                        cnt += 1
                        dcq = float(atom.get('charge'))
                        # subtract Drude charge from DC
                        dcq -= dt['dq']
                        atom.set('charge', f'{dcq:.5f}')
                        # insert DP
                        dp = ET.Element('Atom')
                        if not longname:
                            dp.set('name', 'D' + atname)
                        else:
                            dp.set('name', 'D' + np.base_repr(cnt, base=32))
                        dp.set('core', atname)
                        dp.set('type', 'D-' + attype)
                        dp.set('charge', '{0:.5f}'.format(dt['dq']))
                        residue.insert(i, dp)
                        # no need to add DC-DP bonds: done by OpenMM
                        #bd = ET.Element('Bond')
                        #bd.set('atomName1', atname)
                        #bd.set('atomName2', 'D' + atname)
                        #residue.append(bd)
                        break

        bdforce = self.root.find('HarmonicBondForce')
        db = ET.SubElement(bdforce, 'Bond')
        db.set('class1', 'X')
        db.set('class2', 'DRUD')
        db.set('length', '0.0')
        db.set('k', '{0:.2f}'.format(drude.types[0]['k'] * 100.0))

        nonbondedforce = self.root.find('NonbondedForce')
        dp = ET.SubElement(nonbondedforce, 'Atom')
        dp.set('class', 'DRUD')
        dp.set('sigma', '1.0')
        dp.set('epsilon', '0.0')

        drudeforce = ET.SubElement(self.root, 'DrudeForce')
        for atom in self.root.iter('Type'):
            atname = atom.get('name')
            tok = atname.split('-')
            if atname[0] == 'D' and len(tok) > 3 :
                continue
            ffname = tok[1]            
            for dt in drude.types:
                if ffname == dt['type']:
                    dp = ET.SubElement(drudeforce, 'Particle')
                    dp.set('type1', 'D-' + atname)
                    dp.set('type2', atname)
                    dp.set('charge', '{0:.5f}'.format(dt['dq']))
                    dp.set('polarizability', '{0:.7f}'.format(dt['alpha']/1e3))
                    dp.set('thole', str(dt['thole']/2))
                    break

        ljforce = self.root.find('LennardJonesForce')
        if ljforce:
            dp = ET.SubElement(ljforce, 'Atom')
            dp.set('class', 'DRUD')
            dp.set('sigma', '1.0')
            dp.set('epsilon', '0.0')


# --------------------------------------

def main():
    parser = argparse.ArgumentParser(description = usage,
             formatter_class = argparse.RawTextHelpFormatter)
    parser.add_argument('-a', '--alpha_file', default = 'alpha.ff',
                        help = 'Drude parameter file (default: alpha.ff)')
    parser.add_argument('-e', '--eps', type=float, default = '0.02',
                        help = 'Max DC-DP distance (default: 0.02 A)')
    parser.add_argument('-ix', '--inxml', default = 'field.xml',
                        help = 'input OpenMM xml file (default: field.xml)')
    parser.add_argument('-ox', '--outxml', default = 'field-p.xml',
                        help = 'output OpenMM xml file (default: field-p.xml)')
    parser.add_argument('-ip', '--inpdb', default = 'config.pdb',
                        help = 'PDB file with configuration (default: config.pdb)')
    parser.add_argument('-op', '--outpdb', default = 'config-p.pdb',
                        help = 'PDB file with configuration (default: config-p.pdb)')
    args = parser.parse_args()

    config = Topology(args.inpdb)
    ff = Forcefield(args.inxml)
    drude = Drude(args.alpha_file, config, ff)
    ff.polarize(drude)
    config.polarize(ff, args.eps)
    print(f'{config.natom} atoms {config.ndrude} Drude particles')
    ff.write(args.outxml)       # removes 'core', so use after config.polarize()
    print('polarizable force field written to', args.outxml)
    config.write(args.outpdb)
    print('configuration written to', args.outpdb)

if __name__ == '__main__':
    main()
